version: 2
jobs:
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
      - run:
          name: ssh & deploy
          command: ssh ec2-user@3.113.16.5 '/home/ec2-user/trapla/deploy.sh'

workflows:
    version: 2
    build-deploy:
      jobs:
        - deploy:
            filters:
              branches:
                only: main
