default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: trapla_development


test:
  <<: *default
  database: trapla_test
  
  
production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
